### ISSUE TITLE
Compile failed on Android platform. ifaddrs.h is not found.

### ISSUE THREAD

**Issue by zlargon** [zlargon/lssdp#1]
Android does not have its own native ifaddrs.h implementation (and thus does not have the getifaddrs() function)

#### Compile Log:
```
jni/../../third_party/lssdp/lssdp.c:854:51: fatal error: ifaddrs.h: No such file or directory
 #include <ifaddrs.h>    // getifaddrs, freeifaddrs
                                                   ^
compilation terminated.
make[1]: *** [obj/local/armeabi/objs/bee/__/__/third_party/lssdp/lssdp.o] Error 1
make[1]: Leaving directory `/Users/zlargon/bee/bee/android'
make: *** [libbee_jni] Error 2
```

**Comment by zlargon** [comment]
This issue has bee resolved :+1:

**Comment by avinashkh** [comment]
Hi
How did you resolve this issue?? I am still facing problem 
Thanks

**Comment by zlargon** [comment]
Instead of including `ifaddrs.h`, I used `net/if.h` to get interface information.
Please also check out this commit https://github.com/zlargon/lssdp/commit/9b4568.

**Comment by avinashkh** [comment]
Thanks for information... I will try this approach

 meanwhile i gave a quick try by reading /proc/net/if_inet6  to get Ipv6 address.  Not sure if any issue with this approach but it seems to be working.

found it here
http://domen.ipavec.net/en/get-ip-ipv6-and-mac-addresses-using-ioctl-and-procfs-linux-c

Let me know your opinion on this

**Comment by tmm1** [comment]
FYI `ifaddrs.h` was added to Android in API24
